### ISSUE TITLE
looking for Educative course downloader

### ISSUE THREAD

**Issue by samarthasthan** [wassimbj/educative.io-pdf-downloader#3]
Hey, I am looking for Educative course downloader, i have educative premium account, but i am not able to find any educative downloader also your program is also not working, so can you help me in this? also i you want any course i will download it for you?

**Comment by wassimbj** [comment]
did you download chrome binaries and updated the [L#22](https://github.com/wassimbj/educative.io-pdf-downloader/blob/16b3378bd5410c8daaef662df65b86c59e246daa/main.py#L22) ?

**Comment by samarthasthan** [comment]
i think your code is for windows, i have macos and also educative ask to fill cloudflare captcha after some pages!

**Comment by wassimbj** [comment]
The url is for windows correct, but you can change it. however if educative uses captcha, i believe it's impossible to bypass it

as what the script is doing is accessing the page, take a screenshot and convert it to pdf
